### ISSUE TITLE
Request caindo em handler errado quando se tem um GET com path params

### ISSUE THREAD

**Issue by rAndrade360** [jeffotoni/quick#1]
Quando se cria mais de uma rota GET, sendo uma com path params, todas as requests com esse método estão sendo forçadas para a request que espera os params. Vou exemplificar:

No exemplo abaixo, temos duas rotas GET, sendo uma delas com pathParams:
```go
package main

import (
	"log"
	"net/http"

	"github.com/jeffotoni/quick"
)

func main() {
	app := quick.New()

	app.Use(func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			//This is the first middleware! This guy generate a msgID
			r.Header.Set("Messageid", "12345")
			h.ServeHTTP(w, r)
		})
	})

	app.Get("/v1/customer/:param1/:param2", func(c *quick.Ctx) {
		c.Set("Content-Type", "application/json")

		type my struct {
			Msg string `json:"msg"`
			Key string `json:"key"`
			Val string `json:"val"`
		}

		log.Println(c.Headers["Messageid"])

		c.Status(200).Json(&my{
			Msg: "Quick ❤️",
			Key: c.Param("param1"),
			Val: c.Param("param2"),
		})
	})

	app.Use(func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			//This is the third middleware! This guy blocks request if header contains Block == true
			if r.Header.Get("Block") == "" {
				w.WriteHeader(400)
				w.Write([]byte(`"Message": "send the block header, please! :("`))
				return
			}

			if r.Header.Get("Block") == "true" {
				w.WriteHeader(200)
				w.Write([]byte(`"Message": "quicks block this request :)"`))
				return
			}

			r.Header.Set("Messageid", "12345")
			h.ServeHTTP(w, r)
		})
	})

	app.Get("/v1/blocked", func(c *quick.Ctx) {
		c.Set("Content-Type", "application/json")

		type my struct {
			Msg   string `json:"msg"`
			Block string `json:"block_message"`
		}

		log.Println(c.Headers["Messageid"])

		c.Status(200).Json(&my{
			Msg:   "Quick ❤️",
			Block: c.Headers["Block"][0],
		})
	})

	log.Fatal(app.Listen("0.0.0.0:8080"))
}
```

Nesse caso, todas as requisições GET feitas a aplicação sempre caem na rota `/v1/customer/:param1/:param2`. Exemplo:

Esse caso era para cair na rota `/v1/blocked`
```bash
curl -iv -H "Block: false" localhost:8080/v1/blocked     
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v1/blocked HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Block: false
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: application/json
Content-Type: application/json
< Date: Wed, 22 Feb 2023 19:19:39 GMT
Date: Wed, 22 Feb 2023 19:19:39 GMT
< Content-Length: 49
Content-Length: 49

< 
* Connection #0 to host localhost left intact
{"msg":"Quick ❤️","key":"v1","val":"blocked"}% 
```

Esse caso era para dar um erro de `Not Found` já que a rota não foi declarada
``` bash
curl -iv -H "Block: false" localhost:8080/look/error
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /look/error HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Block: false
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: application/json
Content-Type: application/json
< Date: Wed, 22 Feb 2023 19:21:04 GMT
Date: Wed, 22 Feb 2023 19:21:04 GMT
< Content-Length: 49
Content-Length: 49

< 
* Connection #0 to host localhost left intact
{"msg":"Quick ❤️","key":"look","val":"error"}
```

**Comment by jeffotoni** [comment]
O bug foi corrigido, porém o seus Middlewares me chamaram a atenção para testa-los, como não está 100% os middlewares precisamos testar mais eles e implementa-los..

`curl -iv -H "Block: false" localhost:8080/v1/blocked`

`*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v1/blocked HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Block: false
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: application/json
Content-Type: application/json
< Date: Thu, 23 Feb 2023 04:53:45 GMT
Date: Thu, 23 Feb 2023 04:53:45 GMT
< Content-Length: 46
Content-Length: 46

< 
* Connection #0 to host localhost left intact
{"msg":"Quick ❤️","block_message":"false"}`

`curl -iv -H "Block: false" localhost:8080/v1/blocked/error`

`*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v1/blocked/error HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Block: false
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< Date: Thu, 23 Feb 2023 04:56:04 GMT
Date: Thu, 23 Feb 2023 04:56:04 GMT
< Content-Length: 19
Content-Length: 19

< 
404 page not found
* Connection #0 to host localhost left intact
`
