### ISSUE TITLE
Improvement - Improve tests in GET and POST requests

### ISSUE THREAD

**Issue by marcos-dev88** [jeffotoni/quick#16]
É necessário fazer um update nos testes unitários das requisições GET e POST

Posso ficar com essa issue @jeffotoni ?

**Comment by jeffotoni** [comment]
Yes , manda bala

**Comment by marcos-dev88** [comment]
Realizados os ajustes @jeffotoni ! No PR [improve-16](https://github.com/jeffotoni/quick/pull/17)

**Comment by marcos-dev88** [comment]
Aberto mais um PR para fazer o fix do erro de null pointer: [improve-16](https://github.com/jeffotoni/quick/pull/18)

Quando puder dar uma olhada @jeffotoni :)

**Comment by marcos-dev88** [comment]
Como foi realizado o merge além de ter sido testado após a correção e funcionou, estarei fechando a issue @jeffotoni.
