### ISSUE TITLE
Não está pegando os parametros como values para 

### ISSUE THREAD

**Issue by jeffotoni** [jeffotoni/quick#54]
app.Get("/v1/customer/:param1/:param2", func(c *quick.Ctx) error {
		c.Set("Content-Type", "application/json")

		type my struct {
			Msg string `json:"msg"`
			Key string `json:"key"`
			Val string `json:"val"`
		}

		return c.Status(200).JSON(&my{
			Msg: "Quick ❤️",
			Key: c.Param("param1"),
			Val: c.Param("param2"),
		})
	})
	
	curl -i -XGET localhost:8080/v1/customer/val1/val2
	{"msg":"Quick ❤️","key":"","val":""}

**Comment by marcos-dev88** [comment]
@rAndrade360 Let me finish this bug

**Comment by jeffotoni** [comment]
Agora sim, resolvido.
