### ISSUE TITLE
Bug - GET Params

### ISSUE THREAD

**Issue by marcos-dev88** [jeffotoni/quick#9]
Atualmente estamos tendo um erro ao pegar os parâmetros na request após dos definidos. 

exemplo:

working: /api/:msgID

Not Working: /api/:msg/some

**Comment by jeffotoni** [comment]
`app := quick.New()
 app.Get("/v1/customer/:param1/:param2/product/:param3", QuickHandler)
 app.Get("/v1/customer/:param1/:param2/product/:param3/path1/:param4/path2/:param5", QuickHandler)
`
curl -i -XGET 'localhost:8080/v1/customer/val1/val2/product/val3'
curl -i -XGET 'localhost:8080/v1/customer/val1/val2/product/val3/path1/val4/path2/val5'

**Comment by marcos-dev88** [comment]
@jeffotoni, realizado o ajuste no PR [Bug-09](https://github.com/jeffotoni/quick/pull/12)

**Comment by jeffotoni** [comment]
![image](https://user-images.githubusercontent.com/1092879/221183145-e85f91ca-dc5d-43d1-b332-af6831957d14.png)

**Comment by marcos-dev88** [comment]
Vou verificar, assim que estiver concluído o ajuste mando o PR aqui novamente @jeffotoni .

**Comment by marcos-dev88** [comment]
Boa noite @jeffotoni , realizado o ajuste, segue as evidências:

**path apenas '/'**
`curl -vi -XGET 'http://localhost:8080/val1/val2/val3/some'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /val1/val2/val3/some HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.87.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: application/json
Content-Type: application/json
< Date: Sat, 25 Feb 2023 01:52:20 GMT
Date: Sat, 25 Feb 2023 01:52:20 GMT
< Content-Length: 0
Content-Length: 0

<
* Connection #0 to host localhost left intact`

**Apenas com o path**
`$ curl -vi -XGET 'http://localhost:8080/some'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /some HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.87.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: application/json
Content-Type: application/json
< Date: Sat, 25 Feb 2023 01:51:42 GMT
Date: Sat, 25 Feb 2023 01:51:42 GMT
< Content-Length: 0
Content-Length: 0

<
* Connection #0 to host localhost left intact`

funcionamento com query streing:

`curl -vi -XGET 'http://localhost:8080/some?val=1'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /some?val=1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.87.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: application/json
Content-Type: application/json
< Date: Sat, 25 Feb 2023 02:08:39 GMT
Date: Sat, 25 Feb 2023 02:08:39 GMT
< Content-Length: 0
Content-Length: 0

<
* Connection #0 to host localhost left intact`

**Comment by marcos-dev88** [comment]
Bug resolvido no PR [Bug-9](https://github.com/jeffotoni/quick/pull/15)

**Comment by jeffotoni** [comment]
Continua bugado neste cenário

![image](https://user-images.githubusercontent.com/1092879/221357933-a4b4579d-a6a0-4648-b325-458d2c827774.png)
